/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/5D TENAZAS.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.06, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_111_ARD-geom"].geometry}
          material={materials._111_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_111_ARD-geom_1"].geometry}
          material={materials._111_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_111_ARD-geom_2"].geometry}
          material={materials._111_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/5D TENAZAS.gltf");
